### PR TITLE
pr

### PR DESCRIPTION
**Pull request by Gust1**

### CODE REVIEW

**Comment by LuisFernando100** [comment]
algo

**Comment by LuisFernando100** [comment]
algo

**Comment by LuisFernando100** [comment]
algo

**Comment by LuisFernando100** [comment]
algo

**Comment by LuisFernando100** [comment]
algo

**Comment by LinkedDataCommenter** [comment]
Build Succesful

**Comment by LinkedDataCommenter** [comment]
RDF file missing. Make sure it has the correct format null.rdf<br/>TTL file missing. Make sure it has the correct format null.ttl<br/>PNG file missing. Make sure it has the correct format null.png

**Comment by LinkedDataCommenter** [comment]
Build Succesful

**Pull request closed without merging**
